### ISSUE TITLE
Incidencia: Falta una pregunta al crear votación primaria

### ISSUE THREAD

**Issue by JavierGarCe** [Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Votaciones#17]
Cuando creo una votación primaria de una candidatura aparecen las preguntas para los delegados de cada curso correctamente, pero falta la pregunta de elegir al representante a delegado de centro, ¿no?

**Comment by fraperbar** [comment]
Gracias por avisar, ya se ha arreglado. Ahora puedes comprobar que se hace la pregunta para elegir a delegado de centro, que se añade a voting y también se puede borrar correctamente.
