### ISSUE TITLE
Task002: Fallo en el método "start" de voting

### ISSUE THREAD

**Issue by JavierGarCe** [Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Votaciones#2]
Arreglar el método que al cambiar la clase voting no funciona.

Pasos para replicar el bug:

-Usar la rama feature/task003 donde se ha editado la clase voting
- Desplegar la página en local
- Acceder al panel del administrador
- Crear una votación
- Seleccionar la votación recién creada
- Pulsar en 'start'

Se adjunta el log del servidor: 

- HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /mixnet/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f343b7380d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Y una captura de pantalla:

![image](https://user-images.githubusercontent.com/56033783/102481255-c40b1c80-4061-11eb-84a9-c9514ebc84eb.png)

**Comment by juaferfer11** [comment]
Para arreglar este fallo, se tiene que poner una url válida a la hora de crear el auth de la votación, que en caso de desplegarlo en local sería http://localhost:8000, o http://10.5.0.1:8000 en el caso de desplegarlo con docker.
