### ISSUE TITLE
Incidencia: Error al crear votación general sin primarias previas.

### ISSUE THREAD

**Issue by fraperbar** [Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Votaciones#20]
Si intento crear una votación general antes de hacer las primarias y que por lo tanto estén escogidos los delegados de cada candidatura, da fallo pero sin embargo se crean las preguntas.

Estoy ejecutando en local con Chrome usando la rama feature/task007.

Pasos para replicar el fallo:

    1. Añadir el modelo de autentificación del grupo compañero.
    2. Aplicar migraciones
    3. Correr el servidor 
    4. Entrar en admin
    5. Asegurarse de que la candidatura no tiene representantes o crear una sin ellos
    6. Seleccionar la candidatura y tratar de crear la votación general
    7. Ver que muestra mensaje de fallo
    8. Ir a questions
    9. Ver que se han creado aunque no debían
 
Tal vez se pueda solucionar haciendo una comprobación antes de guardar las questions.

**Comment by JavierGarCe** [comment]
Cierto. Se ha solucionado borrando las preguntas en el except del try/except. Commit: 093c84f8896eedb6f51c19ad635714cb9c6f1959
