### ISSUE TITLE
Incidencia: No se pueden ejecutar las pruebas con el modelo de autentificación

### ISSUE THREAD

**Issue by JavierGarCe** [Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Votaciones#21]
Cuando incorporo el modelo de los compañeros de autentificación las pruebas no se llegan a ejecutar por un fallo en una relación que no soy capaz de solucionar.

Pasos para replicar:

1. Usar la rama feature/task007
2. Incorporar el modelo de los compañeros de autentificación con el voting user
3. Hacer las migraciones
4. Ejecutar las pruebas del módulo voting

Captura de pantalla del fallo:

![image](https://user-images.githubusercontent.com/56033783/102777725-7825e380-4391-11eb-8806-3c8baac5f6be.png)

**Comment by fraperbar** [comment]
He subido a la rama la solución, era un fallo de dependencia en las migraciones debido al "ManyToMany" en el archivo "0003_auto_20180605_0842.py" en este archivo se podia ber que se requería de la api "base" pero que sin embargo no estaba en las dependencias. Te adjunto mis pasos para localizar el error por si pudiera ser de ayuda en un futuro:

  1. Ejecutas las pruebas con "--verbosity=2" (importante para localizar el archivo donde está dando el fallo).
  2. Ves el archivo que falla y vas al mismo.
  3. Si en el archivo hay alguna api en operaciones que no esté en dependencias añade esto a dependencias.
  4. Trata de ejecutar las pruebas nuevamente para ver si se ha solucionado.

Espero haberte servido de ayuda
