### ISSUE TITLE
Incidencia: Error en el serialize de question

### ISSUE THREAD

**Issue by pedcarmor** [Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Votaciones#33]
Según nos han comentado los compañeros de cabina, al intentar acceder a la cabina de votación da un error en las votaciones ya que no se muestran correctamente.

Pasos para replicar:

- Usar la rama develop
- Desplegar en local
- Entrar en el panel de booth
- Muestra error 404 page not found (de esto se encargan los compañeros de cabina). 
- Una vez dentro de booth no se muestran las votaciones.

Para poder mostrar correctamente las votaciones en la cabina, habría que modificar el archivo serialize.py de voting, buscar question = QuestionSerializer(many=False) dentro de la clase VotingSerializer y ponerlo a true.

**Comment by ferromrio** [comment]
Se ha solucionado el problema pero por error se ha subido a la rama develop en lugar de crear una rama fix y luego hacer un  merge a la rama develop
