### ISSUE TITLE
Incidencia: Opciones de la pregunta de delegación en votación general

### ISSUE THREAD

**Issue by pedcarmor** [Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Votaciones#50]
Al crear una votación general automáticamente en la pregunta de la delegación de alumnos se incluyen alumnos con cargos de candidatura cuando no debería pasar.

Pasos para replicar:

- Rama develop
- Desplegar en local
- Crear una votación general a partir de candidaturas con representates
- Ver que hay opciones en la pregunta de delegación que no deberían estar 

Creo que el error se debe a que se están comparando User con VotingUser.

Asignado a @JavierGarCe 
Revisado por @pedcarmor

**Comment by JavierGarCe** [comment]
Se ha corregido en el commit f2bc3bf y está listo para revisión

**Comment by pedcarmor** [comment]
Se ha revisado y aprobado el cambio
