### ISSUE TITLE
Incidencia: no se debería poder empezar una votación si las preguntas y sus opciones no siguen unos criterios mínimos en su redacción

### ISSUE THREAD

**Issue by juaferfer11** [Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Votaciones#69]
Este hecho puede provocar problemas tanto a los métodos de tally como de do_postproc. Además de que no tiene mucho sentido poder crear una votación cuyas preguntas y opciones sean caracteres aleatorios. Básicamente para resolver la incidencia lo que hay que hacer es comprobar que las preguntas y sus opciones siguen un patrón de redacción similar al que se tiene cuando se crean las votaciones automáticamente y que no produzca conflictos con los métodos anteriormente citados.

Asignado a @JavierGarCe 
Revisa @juaferfer11

**Comment by JavierGarCe** [comment]
Se han revisado los tests e incorporado a develop: 9e9d3c5

**Comment by JavierGarCe** [comment]
He cerrado la issue por confusión creyendo que se trataba de otra, vuelvo a abrirla.
